apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty-to-openshift
  labels:
    app: liberty-to-openshift
spec:
  selector:
    matchLabels:
      app: liberty-to-openshift
  template:
    metadata:
      labels:
        app: liberty-to-openshift
    spec:
      containers:
      - name: liberty-to-openshift
        image: image-registry.openshift-image-registry.svc:5000/liberty-to-openshift/liberty-to-openshift:olp-java17-1.0
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: liberty-to-openshift
spec:
  selector:
    app: liberty-to-openshift
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: liberty-to-openshift
spec:
  to:
    kind: Service
    name: liberty-to-openshift	
